sudo: required

language: node_js

cache:
  directories:
    - "Ëœ/.npm"

node_js:
  - '9'

services:
  - docker

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

install:
  - sudo apt-get update
  - sudo apt-get install golang-go -y
  - wget https://dist.ipfs.io/go-ipfs/v0.4.10/go-ipfs_v0.4.10_linux-386.tar.gz
  - tar xvfz go-ipfs_v0.4.10_linux-386.tar.gz
  - echo 'hello' | ./go-ipfs/ipfs add --api /ip4/${IPFS_IP}/tcp/5001/http

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
  on:
    branch: master
    repo: ipfsconsortium/IPFSConsortiumProxy
